# Generated by Django 3.2.9 on 2021-12-01 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('num', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('side', models.CharField(default='Ask', max_length=3)),
                ('px', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('px',),
            },
        ),
    ]
