# Generated by Django 3.2.9 on 2021-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_orders', '0002_rename_orderbook_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('side', 'symbol', 'px'), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.CharField(default='', max_length=15),
        ),
    ]
